### ISSUE TITLE
No such file or directory when running migrate install on windows

### ISSUE THREAD

**Issue by ga0357r** [byjg/php-migration#51]
whenever I run `vendor/bin/migrate install --path vendor/byjg/migration-cli/pob/sql_server sqlsrv://L0v3_Pob_729sd6d8s34d9djh26:'d@g^P455#77%1Yd@g^P455#77%1Yd@g^P455#77%1Y'@sql1/DragonRunner -v` in windows  docker php container environment, it  gives me this error `vendor/bin/migrate: line 1: ../byjg/migration-cli/scripts/migrate: No such file or directory`. This is the `vendor/bin/migrate` script `../byjg/migration-cli/scripts/migrate`.  

However, this works on mac docker php container environment with no issues. Does anyone know how I can fix this, thank you.

**Comment by ga0357r** [comment]
I am also using version 4.2
![image](https://github.com/byjg/php-migration/assets/56434339/f7367cef-50f2-4b8e-be8e-3bc827580be0)

**Comment by ga0357r** [comment]
alright, thank you for your assistance, however, I wont be able to share the whole docker file, only the php section

**Comment by ga0357r** [comment]
alright, this is the docker compose and php dockerfile as well.

### docker compose file

```
version: '3.3'

services:
    web:
        build: 
          context: .
          dockerfile: ./nginx/Dockerfile
        ports:
            - "52379:80"
            - "8080:8080"
            - "5173:5173"
        volumes:
            - ./code:/code
            - ./src:/src
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: .
            dockerfile: php/develop/Dockerfile
        volumes:
            - ./code:/code
            - ./src:/src
            - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
        networks:
            - code-network
    db:
        build:
            context: .
            dockerfile: sqlserver/Dockerfile
        volumes:
            - ./storage/backup:/backup
        ports:
            - "1433:1433"
        networks:
            code-network:
        container_name: sql1
        hostname: sql1
    backup:
        build:
            context: .
            dockerfile: backup-system/Dockerfile
        volumes:
            - ./storage/backup:/backup
        networks:
            code-network:
    mailhog:
      image: mailhog/mailhog
      ports:
        - target: 8025
          published: ${MAILHOG_PUBLISHED_PORT:-8025}
          protocol: tcp
          mode: host
      networks:
        - code-network

networks:
    code-network:
        driver: bridge
```

### php dockerfile

```
FROM php:8.2-fpm-bullseye
WORKDIR /code

# setup composer environment variables
ENV COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/composer

# use composer within php container
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

# Change listen port from www.conf
COPY ./etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/zzz-www.conf
# copy php.ini
COPY ./etc/php/develop/php.ini /usr/local/etc/php/
COPY ./etc/php/develop/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Get repository and install wget and vim
RUN apt-get update && apt-get install -y \
  wget \
  apt-utils \
  gnupg \
  software-properties-common \
  apt-transport-https \
  libxml2-dev \
  unixodbc-dev

# necessário para sqlsrv 
# Install PHP extensions deps
# Install PHP extensions
# install and enable xdebug
# Clean repository
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && wget -qO - https://packages.microsoft.com/config/debian/11/prod.list \
  > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get update \
  && apt-get install --no-install-recommends -y \
  libfreetype6-dev \
  libjpeg62-turbo-dev \
  libmcrypt-dev \
  libpng-dev \
  zlib1g-dev \
  libicu-dev \
  g++ \
  git \ 
  unzip \
  libzip-dev \
  libonig-dev \
  && ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 mssql-tools \
  libaio-dev \
  libmemcached-dev \
  freetds-dev \
  libssl-dev \
  openssl \
  supervisor \
  && pecl install sqlsrv pdo_sqlsrv \
  && pecl install mcrypt-1.0.6 && docker-php-ext-enable mcrypt \
  && pecl install xdebug-3.2.2 && docker-php-ext-enable xdebug \
  && docker-php-ext-install \
  iconv \
  sockets \
  pdo \
  pdo_mysql \
  intl \
  mbstring \
  zip \ 
  bcmath \
  && docker-php-ext-enable \
  sqlsrv \
  pdo_sqlsrv \
  && apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
```
